= Упражнение 1: Увод в обектно-ориентирано програмиране с Java (първа част)

Да се имплементира проста информационна система за управление на футболен клуб с максимум 60 служители. Всеки служител се характеризира с имена, възраст и дата на изтичане на договора.

В клуба са наети три вида служители - футболисти, треньори и помощен персонал. Футболистите допълнително се характеризират с с пост (Защитник, Полузащитник, Вратар, Нападател) и изиграни мачове през съответния месец.
Треньорите могат да бъдат старши или помощник, като за тях се съхранява и броят спечелени титли в кариерата им. Помощният персонал се определя допълнително от заеманата позиция и брой години стаж в отбора.
Системата трябва да поддържа следната функционалност:

1) добавяне на нов футболист, треньор и служител от помощния персонал, ако капацитета на клуба го позволява. 

2) да се извежда списък на всички служители на клуба подредени по дата на изтичане на договора.

3) да се изведат тези служители, които ще са с изтекъл договор към днешна дата.

3) да се определи месечната заплата на даден служител, ако:

	-базовата заплата на всеки служител е както следва: футболист 10000лв, треньор 8000лв и служител от помощния персонал 1000лв.
	
	-за футболистите, допълнително за всеки изигран мач през месеца се добавят по 250лв.
	
	-на старши треньорите с повече от 5 титли в кариерата, месечната заплата се увеличава с 5000лв.
	
	-служителите от помощния персонал получават допълнително по 5% за всяка прослужена година
	
== Hints

1) за да представите и използвате датата на изтичане на договора използвайте класовете от пакета java.time. Повече информация за API-то: 

basic примери за използване на някои от класовете: http://www.journaldev.com/2800/java-8-date-localdate-localdatetime-instant

официална документация; https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html
