= Упражнение 1: Увод в структурите от данни с Java

== Задача: Truck Tour
Представете си че сте камион и маршрута по който минавате е кръг. Има N бензионостанции наредени в този кръг. Всяка петролна станция се характеризира с количество петрол, което може да ви предостави и 
и дистанцията до следващата петролна станция. Представете си, че имате безкраен резервоар. Вие може да започнете вашия маршрут от която искате бензиностанция. Изведете номера на първата бениностанция, стартирайки от където ще може да
преминете по целия маршрут (целия кръг)

== Вход 

На първия ред в конзолата въведете числото N, окайзвайки броя на бензиностанциите.
На следващите N редa въведете 2 числа разделени със space, количеството петрол, което една бензиностанция може да ви даде и дистанцията до следващата бензиностанция 

== Изход
Изведете номера на първата бениностанция, стартирайки от където ще може да
преминете по целия маршрут (целия кръг)

== Пример 
Примерен вход:

	3
	1 5
	10 3
	3 4
	
Примерен изход:
	
	1

